hanwooplz_project/hanwooplz_app/urls.py
from django.urls import path, include
from .views import views, chat_views, comment_views, question_views, project_views, portfolio_views


app_name = 'hanwooplz_app'

urlpatterns = [
    path('', views.main, name='main'),
    path('index/',views.index, name='index'),
    path('write/',views.write, name='write'),
    path('login/', views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path('register/', views.register, name='register'),
    path('find_id/', views.find_id, name='find_id'),
    path('find_pw/', views.find_pw, name='find_pw'),
    path('found_pw/', views.found_pw, name='found_pw'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path("myinfo/<int:user_id>", views.myinfo, name="myinfo"),
    path("post/", views.post, name="post"),
    path("post-list/", views.post_list, name="post_list"),
    path('execute_chatbot/', views.execute_chatbot, name='execute_chatbot'),
    path('send_application/', views.send_application, name='send_application'),
    path('get_notifications/', views.get_notifications, name='get_notifications'),
    path('accept_reject_notification/', views.accept_reject_notification, name='accept_reject_notification'),
    path('mark_notifications_as_read/', views.mark_notifications_as_read, name='mark_notifications_as_read'),
    
    # portfolio_views.py
    path("portfolio-list/", portfolio_views.portfolio_list, name="portfolio_list"),
    path("portfolio/<int:post_portfolio_id>", portfolio_views.portfolio, name="portfolio"),
    path("write-portfolio/", portfolio_views.write_portfolio, name="write_portfolio"),
    path("write-portfolio/<int:post_portfolio_id>", portfolio_views.write_portfolio, name="write_portfolio"),

    # project_views.py
    path("project-list/", project_views.project_list, name="project_list"),
    path("project/<int:post_project_id>", project_views.project, name="project"),
    path("write-project/", project_views.write_project, name="write_project"),
    path("write-project/<int:post_project_id>", project_views.write_project, name="write_project"),
    path("update-status/", project_views.update_views, name="update_status"),

    # question_views.py
    path("question-list/", question_views.question_list, name="question_list"),
    path("question/<int:post_question_id>", question_views.question, name="question"),
    path("write-question/", question_views.write_question, name="write_question"),
    path("write-question/<int:post_question_id>", question_views.write_question, name="write_question"),
    path("write-answer/<int:post_question_id>", question_views.write_answer, name="write_answer"),
    path("write-answer/<int:post_question_id>/<int:post_answer_id>", question_views.write_answer, name="write_answer"),
    path("question-like/<int:post_question_id>", question_views.like, name="question_like"),
    path("question-like/<int:post_question_id>/<int:answer_id>", question_views.like, name="question_like"),
    
    # comment_views.py
    path("api/post/<int:post_id>/comments/", comment_views.CommentList.as_view(), name="comment_list"),
    path("api/comments/<int:comment_id>/", comment_views.CommentDetail.as_view(), name="comment_detail"),
    path("api/comment/<int:pk>/like/", comment_views.CommentLikeView.as_view(), name="comment_like"),
    path("question-test/", comment_views.question_test, name="question_test"),
    path("post-test/", comment_views.post_test, name="post_test"),
    
    # chat_views.py
    path('chat/<int:room_number>/<int:receiver_id>', chat_views.current_chat, name='chat'),
    path('chat-msg/<int:room_number>', chat_views.chat_msg, name='chat_msg'),
]

hanwooplz_project/hanwooplz_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hanwooplz_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.USERIMG_URL, document_root=settings.USERIMG_ROOT)

hanwooplz_project/hanwooplz_app/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic import FormView
from django.http import HttpResponse
from django.http import JsonResponse
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from .forms import *
from .models import *
from .serializers import *
import json
import openai

# Create your views here.
def main(request):
    return render(request, 'main.html')
def index(request):
    return render(request, 'index.html')


# 게시글 작성 화면
def write(request):
    return render(request, 'write.html')
    
# 게시글 수정 화면
# def edit(request, id):
#     post = get_object_or_404(Post, id=id)
#     if post:
#         post.description = post.description.strip()
#     if request.method == "POST":
#         post.title = request.POST['title']
#         post.description = request.POST['description']
#         post.save()
#         return redirect('hanwooplz_app:trade_post', pk=id)

#     return render(request, 'write.html', {'post': post})

def current_chat(request):
    return render(request, "chat.html")

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('hanwooplz_app:login')  # You can change 'login' to the name of your login view.
    else:
        form = CustomUserCreationForm()

    return render(request, 'registration/register.html', {'form': form})

class LoginView(View):
    def get(self, request):
        form = LoginForm()
        context = {"form": form}
        return render(request, "registration/login.html", context)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")  # Redirect to the main page
            else:
                # 로그인 실패 메시지를 추가하고 다시 로그인 페이지를 렌더링
                messages.error(request, "로그인에 실패했습니다. 올바른 아이디와 비밀번호를 입력하세요.")

        context = {"form": form}
        return render(request, "registration/login.html", context)

def log_out(request):
    logout(request)
    return redirect(reverse("hanwooplz_app:login"))

def question_list(request):
    return render(request, "question_list.html")

def question_detail(request):
    return render(request, "question.html")

def create_question(request):
    return render(request, "question_form.html")

def myinfo(request):
    return render(request, "myinfo.html")

def post(request):
    return render(request, "post.html")

class ChatBot():
    def __init__(self, model='gpt-3.5-turbo'):
        self.model = model
        self.messages = []

    def ask(self, question):
        self.messages.append({
            'role': 'user',
            'content': question
        })
        res = self.__ask__()
        return res

    def __ask__(self):
        completion = openai.ChatCompletion.create(
            model=self.model,
            messages=self.messages
        )
        response = completion.choices[0].message['content']
        self.messages.append({
            'role': 'assistant',
            'content': response
        })
        return response

    def show_messages(self):
        return self.messages

    def clear(self):
        self.messages.clear()

def execute_chatbot(request):
    if request.method == "POST":
        data = json.loads(request.body.decode('utf-8'))
        question = data.get('question')
        chatbot = ChatBot()
        response = chatbot.ask(question)
        chat_messages = chatbot.show_messages()
        
        chat_messages_json = [{'role': message['role'], 'content': message['content']} for message in chat_messages]
        
        return JsonResponse({"response": response, "chat_messages": chat_messages_json})
    
    return HttpResponse("Invalid Request")

class CommentList(APIView):
    def get(self, request):
        comments = Comment.objects.all()
        serializer = CommentSerializer(comments, many=True)
        return Response(serializer.data)
    
    def post (self, request):
        author = request.user.id if request.user.is_authenticated else None

        comment_data = {
            "content": request.data.get("content"),
            "author": author,
        }
        serializer = CommentSerializer(data=comment_data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
class CommentDetail(APIView):
    def get(self, request, pk):
        comment = get_object_or_404(comment, pk=pk)
        serializer = CommentSerializer(comment)
        return Response(serializer.data)
    
    def put(self, request, pk):
        comment = get_object_or_404(comment, pk=pk)
        serializer = CommentSerializer(comment, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, pk):
        comment = get_object_or_404(comment, pk=pk)
        comment.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User


# UserProfile.objects.create(

# )

# chat_messages.objects.create(
#         id = 1,
#         chat_room = '1',
#         sender = 'user1',
#         receiver = 'user2',
#         message = '안녕하세요',
#         read_or_not = 'False',
#         created_at="2023-10-23 10:30:00",
# )

tmp_chat_rooms = [
        {
            'id': 1,  # 임의의 채팅 룸 ID
            'post': {
                'title': 'Post 1',  # 게시물 제목
                'author': {
                    'id': 1,  # 게시물 작성자 ID
                    'username': 'User1'  # 게시물 작성자 이름
                }
            },
            'sender': {
                'id': 2,  # 채팅을 보낸 사용자 ID
                'username': 'User2'  # 채팅을 보낸 사용자 이름
            },
            'receiver': {
                'id': 3,  # 채팅을 받은 사용자 ID
                'username': 'User3'  # 채팅을 받은 사용자 이름
            },
            'created_at': '2023-10-20 10:30:00',  # 채팅 룸 생성 일자 및 시간
            # 기타 필요한 데이터 추가
        },
        {
            'id': 2,  # 임의의 채팅 룸 ID
            'post': {
                'title': 'Post 1',  # 게시물 제목
                'author': {
                    'id': 1,  # 게시물 작성자 ID
                    'username': 'User1'  # 게시물 작성자 이름
                }
            },
            'sender': {
                'id': 4,  # 채팅을 보낸 사용자 ID
                'username': 'User4'  # 채팅을 보낸 사용자 이름
            },
            'receiver': {
                'id': 3,  # 채팅을 받은 사용자 ID
                'username': 'User3'  # 채팅을 받은 사용자 이름
            },
            'created_at': '2023-10-20 12:30:00',  # 채팅 룸 생성 일자 및 시간
            # 기타 필요한 데이터 추가
        },
        # 다른 채팅 룸 데이터도 추가 가능
    ]

tmp_chat_messages = [
        {
            'id':1, # 임의의 메세지 ID
            'chat_room':{
                'id': 1,  # 임의의 채팅 룸 ID
                'post': {
                    'title': 'Post 1',  # 게시물 제목
                    'author': {
                        'id': 1,  # 게시물 작성자 ID
                        'username': 'User1'  # 게시물 작성자 이름
                    }
                },
                'sender': {
                    'id': 2,  # 채팅을 보낸 사용자 ID
                    'username': 'User2'  # 채팅을 보낸 사용자 이름
                },
                'receiver': {
                    'id': 3,  # 채팅을 받은 사용자 ID
                    'username': 'User3'  # 채팅을 받은 사용자 이름
                },
                'created_at': '2023-10-20 10:30:00',  # 채팅 룸 생성 일자 및 시간
                # 기타 필요한 데이터 추가
            },
            'sender': {
                    'id': 2,  # 채팅을 보낸 사용자 ID
                    'username': 'User2'  # 채팅을 보낸 사용자 이름
                },
            'receiver': {
                    'id': 3,  # 채팅을 받은 사용자 ID
                    'username': 'User3'  # 채팅을 받은 사용자 이름
                },
            'message': '안녕하세요',
            'read_or_not': 'False',
            'created_at': '2023-10-20 10:30:00',
        },
        {
            'id':2, # 임의의 메세지 ID
            'chat_room':{
                'id': 2,  # 임의의 채팅 룸 ID
                'post': {
                    'title': 'Post 1',  # 게시물 제목
                    'author': {
                        'id': 1,  # 게시물 작성자 ID
                        'username': 'User1'  # 게시물 작성자 이름
                    }
                },
                'sender': {
                    'id': 4,  # 채팅을 보낸 사용자 ID
                    'username': 'User4'  # 채팅을 보낸 사용자 이름
                },
                'receiver': {
                    'id': 3,  # 채팅을 받은 사용자 ID
                    'username': 'User3'  # 채팅을 받은 사용자 이름
                },
                'created_at': '2023-10-20 12:30:00',  # 채팅 룸 생성 일자 및 시간
                # 기타 필요한 데이터 추가
            },
            'sender': {
                    'id': 4,  # 채팅을 보낸 사용자 ID
                    'username': 'User4'  # 채팅을 보낸 사용자 이름
                },
            'receiver': {
                    'id': 3,  # 채팅을 받은 사용자 ID
                    'username': 'User3'  # 채팅을 받은 사용자 이름
                },
            'message': '누구세요',
            'read_or_not': 'False',
            'created_at': '2023-10-20 10:30:00',
        },
        
]

def format_datetime(dt):
    today = timezone.now().date()
    if dt.date() == today:

hanwooplz_project/hanwooplz_app/views/comment_views.py
"""
파일명: comment_views.py
작성자: 양승조 HidSquid97
작성일: 2023. 10. 24.
설명: 댓글 기능을 Django REST Framework를 이용하여 구현

댓글 관리 API 뷰:
- CommentList: 해당 게시물에서 댓글 작성 및 조회
- CommentDetail: 특정 댓글을 수정 및 삭제
- CommentLikeView: 댓글 좋아요 추가 및 취소
"""
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework import status, generics
from rest_framework.views import APIView
from rest_framework.response import Response
from ..serializers import *

class CommentList(APIView):
    def get(self, request, post_id):
        comments = Comment.objects.filter(post=post_id).order_by("created_at")
        serializer = CommentSerializer(comments, many=True)
        return Response(serializer.data)
    
    def post (self, request, post_id):
        comment_data = {
            "content": request.data.get("content"),
        }
        serializer = CommentSerializer(data=comment_data)
        if serializer.is_valid():
            serializer.save(author=self.request.user, post_id=post_id)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
  
class CommentDetail(APIView):
    def get(self, request, comment_id):
        comment = get_object_or_404(Comment, pk=comment_id)
        serializer = CommentSerializer(comment)
        return Response(serializer.data)
    
    def put(self, request, comment_id):
        comment = get_object_or_404(Comment, pk=comment_id)
        serializer = CommentSerializer(comment, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    def delete(self, request, comment_id):
        comment = get_object_or_404(Comment, pk=comment_id)
        comment.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
class CommentLikeView(generics.UpdateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def update(self, request, *args, **kwargs):
        comment = self.get_object()
        user = request.user

        if user in comment.like.all():
            comment.like.remove(user)
            message = "좋아요가 취소되었습니다."
        else:
            comment.like.add(user)
            message = ""

        comment.save()
        comment_data = self.get_serializer(comment).data
        context = {"comment_data": comment_data, "message": message}
        return Response(context, status=status.HTTP_200_OK)
    
# 댓글 테스트 용
def question_test(request):
    return render(request, "question.html")

def post_test(request):
    return render(request, "post.html")

hanwooplz_project/hanwooplz_app/templates/comment.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/comment.css' %}">
<div class="comment-container">
  {% csrf_token %}
  <div class="comment-list">
  </div>
  {% if user.is_authenticated %}
  <form action="" method="post">
    <textarea name="comment" id="comment-input" cols="30" rows="3"></textarea>
    <div id="comment-submit-button-wrapper">
      <button type="button" id="comment-submit-button">댓글 등록</button>
    </div>
  </form>
  {% endif %}
</div>
<script>var currentUser = "{{ user.username }}"</script>

hanwooplz_project/hanwooplz_app/templates/footer.html
{% load static %}
<footer class="footer">
    <h1 class="footer_logo"></h1>
    <img id="animated-gif" src="{% static 'img/hanwoo1.gif' %}" alt="Animated GIF"
        style="max-width: 70px; max-height: 30px;">
</footer>
<script src="{% static 'js/footer.js' %}"></script>

hanwooplz_project/hanwooplz_app/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="2;url=/index/">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <style>
        
    </style>
    <title>저기압일땐 고기앞으로</title>
</head>

<body>
    <div class="navbar">
        <ul>
            {% comment %} <li><a href="{% url 'hanwooplz_app:login' %}">로그인</a></li>
            <li><a href="{% url 'hanwooplz_app:register' %}">회원가입</a></li> {% endcomment %}
        </ul>
    </div>
    <div class="wavy" onclick="window.location.href = 'index';">
        <span style="--i:1">저</span>
        <span style="--i:2">기</span>
        <span style="--i:3">압</span>
        <span style="--i:4">일</span>
        <span style="--i:5">땐</span>
        <span style="--i:6">고</span>
        <span style="--i:7">기</span>
        <span style="--i:8">앞</span>
        <span style="--i:9">으</span>
        <span style="--i:10">로</span>
    </div>
</body>

</html>

hanwooplz_project/hanwooplz_app/templates/question.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/question.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
    <style>
        picture {
            width: 100%;
            background-color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            position: relative;
        }
        
        picture img {
            width: 100%;
            /* height: 150px; */
            object-fit: contain;
            background-color: white;
        }
        
        #deprecated {
            width: 100%;
            height: 100%;
            position: absolute;
            z-index: 1;
            background-color: #777;
            opacity: 0.7;
            display: flex;
            justify-content: center;
            align-items: center;
            color: white;
            font-size: 48px;
        }
        
        .main-container {
            padding-top: 70px;
            padding-bottom: 20px;
            height: auto;
        }
        
        main {
            width: 100%;
            max-width: 600px;
            height: 100%;
        }
        
        .question-container {
            max-width: 100%;
            display: flex;
            flex-direction: column;
            align-items: start;
            gap: 10px;
        }
        
        .question-container:hover {
            transform: scale(1);
        }
        
        .title {
            font-size: 36px;
            height: inherit;
            line-height: normal;
        }
        
        .info-box,
        .content-box {
            display: flex;
            flex-direction: column;
            align-items: start;
        }
        
        .info-title,
        .content-title {
            color: #777;
        }
        
        .info-content,
        .content {
            font-size: large;
            background-color: #eaeaea;
            padding: 5px;
            display: block;
            align-items: center;
            border-radius: 8px;
            line-height: normal;
        }
        
        .content-box {
            width: 100%;
        }
        
        .content {
            width: 100%;
            margin-top: 0px;
        }
        
        .card {
            display: flex;
            flex-direction: column;
            gap: 6px;
        }
        
        .card button {
            display: block;
            margin: 0 auto;
            background-color: #0077b5;
            color: #fff;
            border: none;
            padding: 6px 12px;
            border-radius: 4px;
            font-size: 14px;
            cursor: pointer;
            transition: background-color 0.3s;
            width: 100%;
        }
        
        #status-form {
            height: inherit;
        }
        
        #status-select {
            width: 85px;
            height: inherit;
            border: 0px;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            padding-left: 5px;
        }
        .title-box {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 20px;
            height: 36px;
            width: 100%;
        }
        .project-status {
            width: 85px;
            height: 100%;
            border-radius: 8px;
            background-color: #0077b5;
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        a:hover {
            cursor: pointer;
        }
    </style>
    <title>{{ title }}</title>
</head>

<body>
    {% include "nav.html" %}
    <div class="main-container">
        <main>
            <div class="question-container">
                <h3 class="title">{{ title }}</h3>
                <div class="keyword-conatiner">
                    {% for keyword in keywords %}
                    <div class="keyword">#{{ keyword }} </div>
                    {% endfor %}
                </div>
                <div class="content">{{ content | safe }}</div>
                <div class="subsidiary">
                    <div class="card">
                        작성자: <a href="{% url 'hanwooplz_app:myinfo' author_id %}"><strong>{{ author }}</strong> 님</a>
                        {% if user.is_authenticated and author_id != request.user.id %}
                        <button onclick="window.location.href = '{% url "hanwooplz_app:chat" 0 author_id %}'" style="display: block; margin: 0 auto; background-color: #0077b5; color: #fff; border: none; padding: 6px 12px; border-radius: 4px; font-size: 14px; cursor: pointer; transition: background-color 0.3s;">
                            채팅하기
                        </button>
                        {% elif not user.is_authenticated %}
                        <button onclick="alert('로그인이 필요합니다.')" style="display: block; margin: 0 auto; background-color: #0077b5; color: #fff; border: none; padding: 6px 12px; border-radius: 4px; font-size: 14px; cursor: pointer; transition: background-color 0.3s;">
                            채팅하기
                        </button>
                        {% endif %}
                        <p>작성 일시: {{ created_at }}</p>
                    </div>
                </div>
                <div class="action-buttons">
                    <a href="" id="show-comments">댓글</a>
                    <a href="{% url "hanwooplz_app:question_like" post_question_id %}">추천 {{ like }} 회</a>
                </div>
            </div>
            <div class="button_list_edit">
                {% if author_id == request.user.id %}
                <button class="button-black" onclick="window.location.href = '{% url "hanwooplz_app:write_question" post_question_id %}'">수정하기</button>
                {% endif %}
                {% if user.is_authenticated and not answered %}
                <button class="button-black" onclick="window.location.href = '{% url "hanwooplz_app:write_answer" post_question_id %}'">답변하기</button>
                {% endif %}
                <button class="button-black" onclick="window.location.href = '{% url 'hanwooplz_app:question_list' %}'">목록으로</button>
            </div>
            <div id="comment-wrapper">{% include "comment.html" %}</div>
            <div class="answer-container-wrapper">
                {% for answer in answers %}
                <div class="answer-container"  data-answer-id="{{ answer.answer_id }}">
                    <div class="content">{{ answer.content | safe }}</div>
                    <div class="subsidiary">
                        <div class="card">
                            작성자: <a href="{% url 'hanwooplz_app:myinfo' answer.author_id %}"><strong>{{ answer.username }}</strong> 님</a>
                            {% if user.is_authenticated and answer.author_id != request.user.id %}
                            <button onclick="window.location.href = '{% url "hanwooplz_app:chat" 0 answer.author_id %}'" style="display: block; margin: 0 auto; background-color: #0077b5; color: #fff; border: none; padding: 6px 12px; border-radius: 4px; font-size: 14px; cursor: pointer; transition: background-color 0.3s;">
                                채팅하기
                            </button>
                            {% elif not user.is_authenticated %}
                            <button onclick="alert('로그인이 필요합니다.')" style="display: block; margin: 0 auto; background-color: #0077b5; color: #fff; border: none; padding: 6px 12px; border-radius: 4px; font-size: 14px; cursor: pointer; transition: background-color 0.3s;">
                                채팅하기
                            </button>
                            {% endif %}
                            <p>작성 일시: {{ answer.created_at }}</p>
                        </div>
                    </div>
                    <div class="action-buttons">
                        <a href="" id="unpack-comments">댓글</a>
                        <a href="{% url "hanwooplz_app:question_like" post_question_id answer.id %}">추천 {{ answer.likes }} 회</a>
                    </div>
                    <div id="answer-comment-wrapper">{% include "comment.html" %}</div>
                </div>
                <div class="button_list_edit">
                    {% if answer.author_id == request.user.id %}
                    <button class="button-black" onclick="window.location.href = '{% url "hanwooplz_app:write_answer" post_question_id answer.id %}'">수정하기</button>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </main>

    </div>
    {% include 'footer.html' %}
    {% include 'chatbot.html' %}

</body>
<script>
    var postId = "{{ post_id }}"
    var currentUser = "{{ request.user }}"
    var answerPostIdList = "{{ answer_post_id_list }}"
</script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const showCommentsLink = document.getElementById("show-comments");
        const commentContainer = document.getElementById("comment-wrapper");

        showCommentsLink.addEventListener("click", function (event) {
        event.preventDefault();

        commentContainer.style.display = "block";
        });
    });
</script>
<script src="{% static 'js/comments.js' %}"></script>
<script src="{% static "js/comments2.js" %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        // 댓글 보기 링크 클릭 시 댓글 컨테이너를 보여줌
        const showCommentsLink = document.getElementById("show-comments");
        const commentContainer = document.getElementById("comment-wrapper");
        let is_hidden = true;

        showCommentsLink.addEventListener("click", function (event) {
        event.preventDefault();

        // 댓글 컨테이너를 표시
        if (is_hidden) {
            commentContainer.style.display = "block";
            is_hidden = false;
        } else {
            commentContainer.style.display = "none";
            is_hidden = true;
        }
        
        });
    });
</script>
</html>

hanwooplz_project/hanwooplz_app/templates/write_portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/write.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}" />
    <title>게시글 작성</title>
</head>

<body>

    {% include 'nav.html' %}

    <section class="main">
        <form id="post" method="POST" action="{% if post_portfolio_id %}{% url 'hanwooplz_app:write_portfolio' post_portfolio_id %}{% else %}{% url 'hanwooplz_app:write_portfolio' %}{% endif %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="write-box">
                <input id="title" type="text" name="title" placeholder="제목" value="{{ title }}">
                <p>프로젝트 기간: </p>
                <input id="start_date" type="date" name="start_date" placeholder="시작일" value="{{ start_date }}">
                <p>~</p>
                <input id="end_date" type="date" name="end_date" placeholder="종료일" value="{{ end_date }}">
                <input id="members" type="text" name="members" placeholder="참여인원수" value="{{ members }}">
                <input id="tech_stack" type="text" name="tech_stack" placeholder="사용 기술 스택" value="{{ tech_stack }}">
                <input id="ext_link" type="text" name="ext_link" placeholder="외부 링크" value="{{ ext_link }}">
                <textarea id="content" name="content">{{ content }}</textarea>
            </div>
            <div class="save-button-wrapper">
                {% if post_author_id == request.user.id %}
                  <input type="submit" class="temp-save-button" name="delete-button" value="삭제"/>
                  <input type="submit" class="save-button" value="수정"/>
                {% else %}
                  <input type="submit" class="save-button" value="글 작성"/>
                {% endif %}
              </div>            
        </form>
    </section>
    
    {% include 'footer.html' %}
    
</body>
<script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'js/tinymce.js' %}"></script>
</html>